# Generated by Django 2.0.2 on 2018-02-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.CharField(default='', max_length=200),
        ),
    ]
