# Generated by Django 2.0.2 on 2018-02-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0002_auto_20180223_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
    ]
