# Generated by Django 2.0.2 on 2018-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0003_auto_20180223_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=11),
        ),
    ]
