# Generated by Django 2.0.2 on 2018-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0004_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('IN PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='open', max_length=11),
        ),
    ]
