# Generated by Django 2.0.2 on 2018-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0005_auto_20180224_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_choices',
            field=models.IntegerField(choices=[(0, '-- Select --'), (1, 'Good'), (2, 'Average')], default=1),
        ),
    ]
