# Generated by Django 2.0.2 on 2018-02-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0006_auto_20180224_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_choices',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'Closed')], default=1),
        ),
    ]
