# Generated by Django 2.0.2 on 2018-02-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketMaster', '0007_auto_20180224_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_choices',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'In Progress'), (2, 'Closed')], default=0),
        ),
    ]
